# Generated by Django 4.1.7 on 2023-02-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_created_at_taskhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskhistory",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="tasks.task"
            ),
        ),
    ]
